[package]
name = "{{project-name}}"
edition = "2024"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "1.0"
stm32f4xx-hal = { version = "0.23.0", features = ["stm32f407"] }

# cargo build/run
[profile.dev]
opt-level = 's'
codegen-units = 1

# cargo build/run --release
[profile.release]
opt-level = 's'
codegen-units = 1
lto = 'fat'
debug = 2
